
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  sam-todo-api-array

Transform:
- AWS::Serverless-2016-10-31

Resources:

  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/todo.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example Function URL
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  TodoFunctionUrl:
    Description: "Todo Function URL"
    Value: !GetAtt TodoFunctionUrl.FunctionUrl
